"""Generate kotor/lib/script/routines.ctx and constants.ctx from the game's own nwscript.nss.

    python kotor/tools/py/nwscript_ctx.py

routines.ctx (namespace nwscript): every engine routine NCS's `ACTION n argc` can call, numbered
by declaration order (n), with its result type and its parameters (type, name, default), as
const tables, plus one `const Name: u16 = n` per routine for engine code.
constants.ctx (namespace nwconst): the 1490 constants, `int` as i32, `float` as f32, `string` as
[]u8.

Only names, types, defaults and values are taken from nwscript.nss, never its comments. The
generated files are committed; rerun this after changing the generator.
"""

import os
import re
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
KOTOR = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

import nwscript  # noqa: E402

OUT = os.path.join(KOTOR, 'lib', 'script')

TYPES = ['void', 'int', 'float', 'string', 'object', 'vector', 'effect', 'event', 'location',
         'talent', 'action']

# The bytecode's object constants (CONSTO operands): the compiler's built-ins.
OBJECT_CONSTS = {'OBJECT_SELF': 0, 'OBJECT_INVALID': 1}


def ctx_string(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif 32 <= o < 127:
            out.append(ch)
        else:
            out.append(f'\\x{o:02x}')
    return '"' + ''.join(out) + '"'


def ctx_float(text):
    """A ctxlang f32 literal for an nwscript float literal (`0.75f`, `1.0`, `3.141592`)."""
    v = float(text.rstrip('fF'))
    s = repr(v)
    if 'e' in s or 'E' in s:
        raise ValueError(f'float {text!r} needs exponent syntax')
    return s


def int_value(text, consts):
    t = text.strip()
    if re.fullmatch(r'-?\d+', t):
        return int(t)
    if re.fullmatch(r'-?0[xX][0-9a-fA-F]+', t):
        return int(t, 16)
    if t in consts:
        c = consts[t]
        return int_value(c.value, consts)
    raise ValueError(f'cannot evaluate int {text!r}')


def default_literal(ptype, d, consts):
    if d is None:
        return 'Default::none'
    t = nwscript.norm_type(ptype)
    if t == 'int':
        return f'Default::int{{ v = {int_value(d, consts)} }}'
    if t == 'float':
        return f'Default::float{{ v = {ctx_float(d)} }}'
    if t == 'string':
        if not (d.startswith('"') and d.endswith('"')):
            raise ValueError(f'string default {d!r}')
        return f'Default::string{{ s = {ctx_string(d[1:-1])} }}'
    if t == 'object':
        if d in OBJECT_CONSTS:
            return f'Default::object{{ constant = {OBJECT_CONSTS[d]} }}'
        # SpeakOneLinerConversation's oTokenTarget=OBJECT_TYPE_INVALID: an int constant used as
        # an object, which the compiler would push as that CONSTO operand.
        return f'Default::object{{ constant = {int_value(d, consts)} }}'
    if t == 'vector':
        m = re.fullmatch(r'\[\s*([^,\]]+)\s*,\s*([^,\]]+)\s*,\s*([^,\]]+)\s*\]', d)
        if not m:
            raise ValueError(f'vector default {d!r}')
        x, y, z = (ctx_float(g) for g in m.groups())
        return f'Default::vector{{ x = {x}, y = {y}, z = {z} }}'
    raise ValueError(f'no default representation for {ptype} = {d!r}')


HEADER = """// GENERATED by kotor/tools/py/nwscript_ctx.py from the game's nwscript.nss: do not edit.
"""


def write_routines(routines, consts):
    params = []
    rows = []
    for r in routines:
        first = len(params)
        required = 0
        for p in r.params:
            if p.default is None:
                required += 1
            params.append(p)
        rows.append((r, first, len(r.params), required))
    lines = [HEADER.rstrip('\n'), """//
// The engine routines a script calls with NCS's `ACTION n argc` (docs/formats/nwscript.md): n is
// the routine's place among nwscript.nss's prototypes, from 0, and the table below is in that
// order. A routine's parameters are PARAMS[first..first + count]; the first `required` have no
// default. Old scripts may pass fewer arguments than `count` (never fewer than `required`, except
// two AddPartyMember calls): the engine fills the rest from the defaults.
//
//   let r = nwscript::ROUTINES[routine]                 // routine: u16, below COUNT
//   let p = nwscript::PARAMS[r.first + i]
//   if routine == nwscript::DelayCommand { ... }
namespace nwscript {
    // A parameter's or a result's type. `action` is a parameter only: the code a STORE_STATE
    // saved, which takes no stack cells. A vector takes three cells; the rest one.
    enum Type: u8 { void, int, float, string, object, vector, effect, event, location, talent, action }

    // A parameter's default. An object default is the bytecode constant the compiler pushes for
    // it (CONSTO's operand): 0 is OBJECT_SELF, any other value OBJECT_INVALID.
    union Default {
        none,
        int{ v: i32 },
        float{ v: f32 },
        string{ s: []u8 },
        object{ constant: i32 },
        vector{ x: f32, y: f32, z: f32 },
    }

    struct Param { kind: Type, name: []u8, default: Default }

    struct Routine { name: []u8, ret: Type, first: u16, count: u8, required: u8 }
""".rstrip('\n')]
    lines.append('')
    lines.append(f'    const COUNT: u16 = {len(routines)}')
    lines.append('')
    lines.append(f'    const ROUTINES: [{len(routines)}]Routine = [')
    for r, first, count, required in rows:
        ret = nwscript.norm_type(r.ret)
        lines.append(f'        Routine{{ name = {ctx_string(r.name)}, ret = Type::{ret}, '
                     f'first = {first}, count = {count}, required = {required} }},  // {r.index}')
    lines.append('    ]')
    lines.append('')
    lines.append(f'    const PARAMS: [{len(params)}]Param = [')
    for p in params:
        t = nwscript.norm_type(p.type)
        lines.append(f'        Param{{ kind = Type::{t}, name = {ctx_string(p.name)}, '
                     f'default = {default_literal(p.type, p.default, consts)} }},')
    lines.append('    ]')
    lines.append('')
    lines.append('    // Each routine\'s number, by its nwscript.nss name.')
    for r in routines:
        lines.append(f'    const {r.name}: u16 = {r.index}')
    lines.append('}')
    path = os.path.join(OUT, 'routines.ctx')
    with open(path, 'w', encoding='ascii', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    return path, len(params)


def write_constants(constants):
    by_name = {c.name: c for c in constants}
    lines = [HEADER.rstrip('\n'), """//
// nwscript.nss's constants. The compiler inlined them into the scripts, so the VM never needs
// them; the engine does, to agree with the scripts on what each number means (most are rows of a
// 2DA table or engine enums). An `int` is an i32, a `float` an f32.
namespace nwconst {""".rstrip('\n')]
    for c in constants:
        t = nwscript.norm_type(c.type)
        if t == 'int':
            lines.append(f'    const {c.name}: i32 = {int_value(c.value, by_name)}')
        elif t == 'float':
            v = nwscript.constant_value(c, by_name)
            lines.append(f'    const {c.name}: f32 = {ctx_float(v)}')
        elif t == 'string':
            v = c.value
            if not (v.startswith('"') and v.endswith('"')):
                raise ValueError(f'string constant {c.name} = {v!r}')
            lines.append(f'    const {c.name}: []u8 = {ctx_string(v[1:-1])}')
        else:
            raise ValueError(f'constant {c.name} of type {t}')
    lines.append('}')
    path = os.path.join(OUT, 'constants.ctx')
    with open(path, 'w', encoding='ascii', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    return path


def main(argv):
    text = nwscript.source()
    routines = nwscript.load_routines(text)
    constants = nwscript.load_constants(text)
    consts = {c.name: c for c in constants}
    os.makedirs(OUT, exist_ok=True)
    rp, nparams = write_routines(routines, consts)
    cp = write_constants(constants)
    print(f'{rp}: {len(routines)} routines, {nparams} parameters')
    print(f'{cp}: {len(constants)} constants')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
